export const ELEMENT_MOUSE_ENTER = 'ELEMENT_MOUSE_ENTER';
export const ELEMENTS_LOAD = 'ELEMENTS_LOAD';
export const ELEMENT_CLICK = 'ELEMENT_CLICK';
export const FILTER_BUTTON_CLICK = 'FILTER_BUTTON_CLICK';
export const SHOW_SPINNER = 'SHOW_SPINNER';
export const HIDE_SPINNER = 'HIDE_SPINNER';
